[project]
name = "mcp-ntopng"
version = "0.1.0"
description = "An MCP Server for ntopng"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.3.0",
    "python-dotenv>=1.0.1",
    "clickhouse-driver>=0.2.5",
    "pip-system-certs>=4.0",
    "requests>=2.32.3",
]
